# Generated by Django 4.0.3 on 2022-03-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stack',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Технология (Stack)', 'verbose_name_plural': 'Технологии'},
        ),
        migrations.AddField(
            model_name='stack',
            name='wiki',
            field=models.URLField(null=True, verbose_name='Википедия'),
        ),
    ]
